# Generated by Django 6.0.2 on 2026-02-25 04:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='idade',
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.autor'),
        ),
    ]
