# Generated by Django 6.0.2 on 2026-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='livros', to='livros.autor'),
        ),
    ]
